// <auto-generated />
using System;
using LibWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibWEB.Migrations
{
    [DbContext(typeof(LibContext))]
    partial class LibContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("LibWEB.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Country")
                        .HasColumnType("int")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Country" }, "country");

                    b.ToTable("author", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.AuthorPrintPublishing", b =>
                {
                    b.Property<int?>("Author")
                        .HasColumnType("int")
                        .HasColumnName("author");

                    b.Property<int>("PrintPublishing")
                        .HasColumnType("int")
                        .HasColumnName("print_publishing");

                    b.HasKey("Author", "PrintPublishing");

                    b.HasIndex(new[] { "Author" }, "author");

                    b.HasIndex(new[] { "PrintPublishing" }, "print_publishing");

                    b.ToTable("author_print_publishing", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("NameGenre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_genre");

                    b.HasKey("Id");

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.GenrePrintPublishing", b =>
                {
                    b.Property<int>("Genre")
                        .HasColumnType("int")
                        .HasColumnName("genre");

                    b.Property<int>("PrintPublishing")
                        .HasColumnType("int")
                        .HasColumnName("print_publishing");

                    b.HasKey("Genre", "PrintPublishing");

                    b.HasIndex(new[] { "Genre" }, "genre");

                    b.HasIndex(new[] { "PrintPublishing" }, "print_publishing")
                        .HasDatabaseName("print_publishing1");

                    b.ToTable("genre_print_publishing", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Giving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly>("GivingDate")
                        .HasColumnType("date")
                        .HasColumnName("giving_date");

                    b.Property<int>("Reader")
                        .HasColumnType("int")
                        .HasColumnName("reader");

                    b.Property<DateOnly?>("ReceivingDate")
                        .HasColumnType("date")
                        .HasColumnName("receiving_date");

                    b.Property<DateOnly>("ReceivingDeadlineDate")
                        .HasColumnType("date")
                        .HasColumnName("receiving_deadline_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Reader" }, "reader");

                    b.ToTable("giving", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.GivingPrintPublishing", b =>
                {
                    b.Property<int>("Giving")
                        .HasColumnType("int")
                        .HasColumnName("giving");

                    b.Property<int>("PrintPublishing")
                        .HasColumnType("int")
                        .HasColumnName("print_publishing");

                    b.HasKey("Giving", "PrintPublishing");

                    b.HasIndex(new[] { "Giving" }, "giving");

                    b.HasIndex(new[] { "PrintPublishing" }, "print_publishing")
                        .HasDatabaseName("print_publishing2");

                    b.ToTable("giving_print_publishing", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Preorder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("GivingDeadlineDate")
                        .HasColumnType("date")
                        .HasColumnName("giving_deadline_date");

                    b.Property<int>("Reader")
                        .HasColumnType("int")
                        .HasColumnName("reader");

                    b.Property<string>("Status")
                        .HasColumnType("enum('created','done','archived')")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Reader" }, "reader")
                        .HasDatabaseName("reader1");

                    b.ToTable("preorder", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.PreorderPrintPublishing", b =>
                {
                    b.Property<int>("Preorder")
                        .HasColumnType("int")
                        .HasColumnName("preorder");

                    b.Property<int>("PrintPublishing")
                        .HasColumnType("int")
                        .HasColumnName("print_publishing");

                    b.HasKey("Preorder", "PrintPublishing");

                    b.HasIndex(new[] { "Preorder" }, "preorder");

                    b.HasIndex(new[] { "PrintPublishing" }, "print_publishing")
                        .HasDatabaseName("print_publishing3");

                    b.ToTable("preorder_print_publishing", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.PrintPublishing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int")
                        .HasColumnName("age_restriction");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageId")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Numbers")
                        .HasColumnType("int")
                        .HasColumnName("numbers");

                    b.Property<int>("YearOfPublishing")
                        .HasColumnType("int")
                        .HasColumnName("year_of_publishing");

                    b.HasKey("Id");

                    b.ToTable("print_publishing", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("patronymic");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("reader", (string)null);
                });

            modelBuilder.Entity("LibWEB.Models.Author", b =>
                {
                    b.HasOne("LibWEB.Models.Country", "CountryNavigation")
                        .WithMany("Authors")
                        .HasForeignKey("Country")
                        .IsRequired()
                        .HasConstraintName("author_ibfk_1");

                    b.Navigation("CountryNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.AuthorPrintPublishing", b =>
                {
                    b.HasOne("LibWEB.Models.Author", "AuthorNavigation")
                        .WithMany()
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("author_print_publishing_ibfk_1");

                    b.HasOne("LibWEB.Models.PrintPublishing", "PrintPublishingNavigation")
                        .WithMany()
                        .HasForeignKey("PrintPublishing")
                        .IsRequired()
                        .HasConstraintName("author_print_publishing_ibfk_2");

                    b.Navigation("AuthorNavigation");

                    b.Navigation("PrintPublishingNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.GenrePrintPublishing", b =>
                {
                    b.HasOne("LibWEB.Models.Genre", "GenreNavigation")
                        .WithMany()
                        .HasForeignKey("Genre")
                        .IsRequired()
                        .HasConstraintName("genre_print_publishing_ibfk_1");

                    b.HasOne("LibWEB.Models.PrintPublishing", "PrintPublishingNavigation")
                        .WithMany()
                        .HasForeignKey("PrintPublishing")
                        .IsRequired()
                        .HasConstraintName("genre_print_publishing_ibfk_2");

                    b.Navigation("GenreNavigation");

                    b.Navigation("PrintPublishingNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.Giving", b =>
                {
                    b.HasOne("LibWEB.Models.Reader", "ReaderNavigation")
                        .WithMany("Givings")
                        .HasForeignKey("Reader")
                        .IsRequired()
                        .HasConstraintName("giving_ibfk_1");

                    b.Navigation("ReaderNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.GivingPrintPublishing", b =>
                {
                    b.HasOne("LibWEB.Models.Giving", "GivingNavigation")
                        .WithMany()
                        .HasForeignKey("Giving")
                        .IsRequired()
                        .HasConstraintName("giving_print_publishing_ibfk_1");

                    b.HasOne("LibWEB.Models.PrintPublishing", "PrintPublishingNavigation")
                        .WithMany()
                        .HasForeignKey("PrintPublishing")
                        .IsRequired()
                        .HasConstraintName("giving_print_publishing_ibfk_2");

                    b.Navigation("GivingNavigation");

                    b.Navigation("PrintPublishingNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.Preorder", b =>
                {
                    b.HasOne("LibWEB.Models.Reader", "ReaderNavigation")
                        .WithMany("Preorders")
                        .HasForeignKey("Reader")
                        .IsRequired()
                        .HasConstraintName("preorder_ibfk_1");

                    b.Navigation("ReaderNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.PreorderPrintPublishing", b =>
                {
                    b.HasOne("LibWEB.Models.Preorder", "PreorderNavigation")
                        .WithMany()
                        .HasForeignKey("Preorder")
                        .IsRequired()
                        .HasConstraintName("preorder_print_publishing_ibfk_1");

                    b.HasOne("LibWEB.Models.PrintPublishing", "PrintPublishingNavigation")
                        .WithMany()
                        .HasForeignKey("PrintPublishing")
                        .IsRequired()
                        .HasConstraintName("preorder_print_publishing_ibfk_2");

                    b.Navigation("PreorderNavigation");

                    b.Navigation("PrintPublishingNavigation");
                });

            modelBuilder.Entity("LibWEB.Models.Country", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("LibWEB.Models.Reader", b =>
                {
                    b.Navigation("Givings");

                    b.Navigation("Preorders");
                });
#pragma warning restore 612, 618
        }
    }
}
